### ISSUE TITLE
test is out of date

### ISSUE THREAD

**Issue by jpatel71** [awslabs/aws-codepipeline-jenkins-aws-codedeploy_linux#1]
looks like new default httpd for the demo fleet created by the code deploy demo starts httpd on 80 instead of 8000, so the test needs to be updated to test without the port number in order for the demo instructions to work

**Comment by biagic** [comment]
Thank you for the head's up, I'll update the repo.

**Comment by biagic** [comment]
I've updated the test script: https://github.com/awslabs/aws-codepipeline-jenkins-aws-codedeploy_linux/commit/9cff58a029278b09587593010a9d4841a7d34b6f

Thanks
